import { ReactNode } from "react";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./component/navbar";

type RootLayoutProps = {
  children: ReactNode; 
};

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className="h-full flex overflow-hidden">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="h-full flex overflow-hidden bg-gray-100">
            {children}
        </div>
      </body>
    </html>
  );
}
